### ISSUE TITLE
alphaplinkpython installation fails under Linux Mint/Python 3.10

### ISSUE THREAD

**Issue by Npaffen** [AlphaGenes/AlphaFamImpute#4]
When I try to install alphaplinkpython via pip I recieve the follwoing error message. I was unable to fix this. Reproducible under Python 3.10 with Linux Kernel 5.15.0-56-generic by running:

`pip install alphaplinkpython
`
Stacktrace of the error:
```
Collecting alphaplinkpython
  Using cached alphaplinkpython-0.0.5.tar.gz (283 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-i9uppgw3/alphaplinkpython_09e8cea2ebda43a1a92c62826bed8a6d/setup.py", line 96, in <module>
          ext_modules=cythonize(ext_modules, gdb_debug=True),
        File "/home/oem/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/home/oem/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/home/oem/.local/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'alphaplinkpython/cpp_src/PlinkWriter.pyx' doesn't match any files
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```

**Comment by gregorgorjanc** [comment]
I think this should be sorted as part of https://github.com/AlphaGenes/AlphaFamImpute/issues/2, but will leave this open so we can test this at some point

**Comment by sergiogonmoll** [comment]
I have the same issue, although some of the lines where the installation fails are different. Here is the message I get:

(first_env) [p309374@login2 AlphaImpute2]$ python3 -m pip install alphaplinkpython
Collecting alphaplinkpython
  Using cached alphaplinkpython-0.0.5.tar.gz (283 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2dzuldj0/alphaplinkpython_ea57a8b38aa24aa3a3aa29125aa31a79/setup.py", line 96, in <module>
          ext_modules=cythonize(ext_modules, gdb_debug=True),
        File "/scratch/p309374/venvs/first_env/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 990, in cythonize
          module_list, module_metadata = create_extension_list(
        File "/scratch/p309374/venvs/first_env/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 825, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "/scratch/p309374/venvs/first_env/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 119, in nonempty
          raise ValueError(error_msg)
      ValueError: 'alphaplinkpython/cpp_src/PlinkWriter.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
